### ISSUE TITLE
Integrate Plausible analytics

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1105]
`<script defer data-domain="tempus.finance" src="https://plausible.io/js/plausible.js%22%3E</script>`

**Comment by irinelT** [comment]
Plausible analytics is set up for Production environment `data-domain="tempus.finance"`, not for Test environment.
Is it possible to use variable URL, different for each environment so that it can be tested before going to Production environment? There should be `data-domain="tempus-app-stage.web.app"` I think.

**Comment by danieledamiani** [comment]
In general it's doable but for our specific configuration it'd require some extra work

**Comment by ShawTim** [comment]
remove the Plausible integration

**Comment by ShawTim** [comment]
close this since this task no longer valid and changes has been reverted. use #1129 instead
