### ISSUE TITLE
Provide Liquidity failed

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1212]
**Description**

**To Reproduce**
1. Navigate to [test environment](https://tempus-app-stage.web.app/).
2. Expand ETH pool.
3. Manage.
4. Provide Liquidity.
5. Enter 1000 Capitals value.
6. Approve both Capitals and Yields.
7. Execute

**Expected behavior**
Liquidity Deposit was successful.

**Actual behavior**
Liquidity Deposit failled.

**Screenshots**
![image](https://user-images.githubusercontent.com/98878781/159051776-455e71b7-9f6a-4261-9030-6a3f3ab904b9.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Tempus Ethereum Fork
URL: https://tempus-app-stage.web.app/

**Additional context**
Detail console log:
[provide liquidity fail.log](https://github.com/tempus-finance/tempus-app/files/8306479/provide.liquidity.fail.log)

**Comment by lazarmitic** [comment]
Ratio of tokens seems way off here, when you fill in the principals, yields are populated automatically for you, right?

**Comment by irinelT** [comment]
Yes, its automatically populate and that why I don't have that step in "To Reproduce" section.

**Comment by lazarmitic** [comment]
In that case something is wrong with auto population of number of assets. I will try to reproduce.

**Comment by lazarmitic** [comment]
I'm not able to reproduce this issue, one thing that I can think of is that for some reason current pool balance is not loaded immediately after you open provide liquidity screen, because of this pool token ratio is not calculated properly and auto populate does not work properly.

Since this is not related to matured pools and it's not a regression I would move this task to 2.2. @irinelT can you try to reproduce again and if everything works I would say it's safe to move this to 2.2.
