### ISSUE TITLE
Dashboard - if Fantom is selected, only show maturity (and other data) in parent row in relation to Fantom

### ISSUE THREAD

**Issue by davgarai** [tempus-finance/tempus-app#964]
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/78982233/153391871-39847e9d-2ce1-4168-8b90-57f3560c17bb.png">

**Comment by lazarmitic** [comment]
@irinelT if parent row has multiple children it will display date for child pool that will mature next and child pool that will mature last  (in this format `1.10.2021 - 1.12.2022`)

If parent row only has one child item (like in the screenshot), it will not display a range of maturity date (because there is only one child item), it will just show a single date from that single item.

This is how the dashboard was designed, I agree with you that data is duplicated, but that's how it is (all other rows are also duplicated in case parent row has single child item).
